import { ExchangeRanking } from './types';

export const CMC_EXCHANGES: ExchangeRanking[] = [
  {
    id: 'binance',
    rank: 1,
    name: 'Binance',
    logo: 'https://assets.coingecko.com/markets/images/52/small/binance.jpg',
    score: 9.9,
    volume24hUsd: 18450920400,
    avgLiquidity: 915,
    weeklyVisits: '14.2M',
    marketsCount: 1684,
    coinsCount: 395,
    fiatSupported: ['USD', 'EUR', 'GBP', 'BRL', 'AUD', 'TRY'],
  },
  {
    id: 'bybit',
    rank: 2,
    name: 'Bybit',
    logo: 'https://assets.coingecko.com/markets/images/698/small/bybit_spot.png',
    score: 9.1,
    volume24hUsd: 6840120800,
    avgLiquidity: 840,
    weeklyVisits: '6.8M',
    marketsCount: 840,
    coinsCount: 310,
    fiatSupported: ['USD', 'EUR', 'GBP', 'BRL'],
  },
  {
    id: 'coinbase',
    rank: 3,
    name: 'Coinbase Exchange',
    logo: 'https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png',
    score: 8.9,
    volume24hUsd: 4920840000,
    avgLiquidity: 880,
    weeklyVisits: '4.5M',
    marketsCount: 420,
    coinsCount: 260,
    fiatSupported: ['USD', 'EUR', 'GBP'],
  },
  {
    id: 'okx',
    rank: 4,
    name: 'OKX',
    logo: 'https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20211105171545.png',
    score: 8.7,
    volume24hUsd: 4120800000,
    avgLiquidity: 790,
    weeklyVisits: '3.9M',
    marketsCount: 650,
    coinsCount: 320,
    fiatSupported: ['USD', 'EUR', 'BRL', 'AUD'],
  },
  {
    id: 'kraken',
    rank: 5,
    name: 'Kraken',
    logo: 'https://assets.coingecko.com/markets/images/29/small/kraken.jpg',
    score: 8.5,
    volume24hUsd: 1950400000,
    avgLiquidity: 810,
    weeklyVisits: '2.1M',
    marketsCount: 710,
    coinsCount: 280,
    fiatSupported: ['USD', 'EUR', 'GBP', 'CAD', 'JPY', 'CHF'],
  },
  {
    id: 'kucoin',
    rank: 6,
    name: 'KuCoin',
    logo: 'https://assets.coingecko.com/markets/images/61/small/kucoin.png',
    score: 8.2,
    volume24hUsd: 1650900000,
    avgLiquidity: 720,
    weeklyVisits: '2.4M',
    marketsCount: 1240,
    coinsCount: 780,
    fiatSupported: ['USD', 'EUR'],
  },
];
